export const Users = [
    {
        id: 6,
        profilePicture: '/Board_images/farmer1.jpg',
        userName: 'דוד כהן',
    },
    {
        id: 2,
        profilePicture: '/Board_images/farm1.jpeg',
        userName: 'משק הגולן',
    },
    {
        id: 3,
        profilePicture: '/Board_images/fruitsandvegies.avif',
        userName: 'Fruits 4 U' ,
    },
    {
        id: 4,
        profilePicture: '/Board_images/cheeseFarm.png',
        userName: 'משק גבינת מולדת',
    },
    {
        id: 5,
        profilePicture: '/Board_images/farm2.jpg',
        userName: 'משק ירק ירוק',
    },
    {
        id: 1,
        profilePicture: '/Board_images/beeFarm.jpeg',
        userName: 'משק דבורים דבורי',
    }
]

export const Posts = [
    {
        id:1,
        desc: 'דבש דבורים טבעי טהור, מחיר השקה של 50 ש"ח לצנצנת קטנה, 74 ש"ח לצנצנת גדולה',
        posted: "לפני 5 דק'",
        date: 'תאריכים: 3.5 - 12.5',
        price: 'טווח מחירים: 50-74 ש"ח',
        location: 'מיקום: משק דבורים דבורי, דימונה',
        time: '10:00-17:00',
        userId: 1,
        comment: 2,
        avgScore: 3.8,
        voters: 2,
    },
    {
        id:2,
        desc: "מביאים אליכם מלפפונים ישר מהשדה, יחד עם יתר הירקות המעולים שגידלנו. משק הגולן- פותחים דוכן חגיגי בבאר שבע. מארז מיני ירקות קטן מתנה ל-100 הקונים הראשונים, בהצגת מודעה זו.",
        photo: '/Board_images/cucumbers.webp',
        posted: "לפני 35 דק'",
        date: "תאריכים: 1-4.5",
        price: 'טווח מחירים: 5-12 לק"ג',
        location: 'מיקום: גרנד קניון באר שבע',
        time: '07:00-14:00',
        userId: 2,
        comment: 5,
        avgScore: 4.4,
        voters: 9,
    },
    {
        id:3,
        desc: "מארז פירות מפנק, כולל פירות יבשים. פירוט תכולת המארז: מלון,אבטיח,קיווי,קרמבולה,משמש,תותים,פסיפלורה,ענבים ירוקים,ענבים שחורים. בואו לבקר בדוכן שלנו בקניון חולון",
        photo: '/Board_images/fruits.jpg',
        posted: "לפני שעה",
        date: 'תאריכים: כל שישי',
        price: 'טווח מחירים: 200 ש"ח',
        location: 'מיקום: קניון חולון',
        time: '10:00-13:00',
        userId: 3,
        comment: 9,
        avgScore: 4.2,
        voters: 4,
    },
    {
        id:4,
        desc: 'פלטת גבינות זוגית במבצע לכבוד חג השבועות, 240 ש"ח בלבד, במקום 320 ש"ח. למציג מודעה זו במשק שלנו.',
        photo: '/Board_images/cheese.webp',
        posted: 'לפני 3 שעות', 
        date: "תאריכים: 30.4-14.5",
        price: 'טווח מחירים: 240 ש"ח',
        location: 'מיקום: משק גבינת מולדת, חצור הגלילית',
        time: '11:00-15:00',
        userId: 4,
        comment: 15,
        avgScore: 4.5,
        voters: 11,
    },
    {
        id: 5,
        desc: "מכירת חיסול! מוזמנים להגיע אלינו ולהנות מהירקות המעולים שלנו, לפני שנזרקים עקב חוסר מקום במדפים. המחירים זולים בטירוף!!",
        posted: 'לפני 2 ימים',
        date: 'תאריכים: 27.4-1.5',
        price: 'טווח מחירים: 4.7 - 10.5 ש"ח לק"ג',
        location: "מיקום: משק ירק ירוק, אזור",
        time: '09:00-13:00',
        userId: 5,
        comment: 6,
        avgScore: 4.0,
        voters: 3,
    },
    {
        id:6,
        desc: "עגבניות אורגניות בזיל הזול",
        photo: '/Board_images/fresh_tomatoes.jpg',
        posted: 'לפני 3 ימים',
        date: 'תאריכים: 18-20.5',
        price: 'טווח מחירים: 5.9 ש"ח לק"ג',
        location: 'מיקום: שוק הכרמל, תל אביב',
        time: '11:00-18:00',
        userId: 6,
        comment: 1,
        avgScore: 3.8,
        voters: 10,
    },
]